import { DocumentArrowDownIcon } from '@heroicons/react/24/outline';
import toast from 'react-hot-toast';

interface Message {
  role: 'user' | 'assistant';
  content: string;
}

interface ExportChatProps {
  messages: Message[];
  documentName?: string;
}

const ExportChat: React.FC<ExportChatProps> = ({ messages, documentName }) => {
  const handleExport = async () => {
    if (messages.length === 0) {
      toast.error('No messages to export');
      return;
    }

    // Create HTML content for the PDF
    const date = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Chat Export - ${documentName || 'Document AI'}</title>
        <style>
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.6;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
            color: #333;
          }
          .header {
            border-bottom: 2px solid #3b82f6;
            padding-bottom: 20px;
            margin-bottom: 30px;
          }
          .header h1 {
            color: #1e40af;
            margin: 0 0 10px 0;
            font-size: 24px;
          }
          .header .meta {
            color: #64748b;
            font-size: 14px;
          }
          .message {
            margin-bottom: 24px;
            padding: 16px;
            border-radius: 8px;
          }
          .message.user {
            background: #eff6ff;
            border-left: 4px solid #3b82f6;
          }
          .message.assistant {
            background: #f0fdf4;
            border-left: 4px solid #22c55e;
          }
          .message .role {
            font-weight: 600;
            margin-bottom: 8px;
            font-size: 12px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
          }
          .message.user .role {
            color: #3b82f6;
          }
          .message.assistant .role {
            color: #22c55e;
          }
          .message .content {
            white-space: pre-wrap;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            color: #94a3b8;
            font-size: 12px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>📄 Chat Export${documentName ? ` - ${documentName}` : ''}</h1>
          <div class="meta">
            <div>Exported: ${date}</div>
            <div>Messages: ${messages.length}</div>
          </div>
        </div>
        
        ${messages.map(msg => `
          <div class="message ${msg.role}">
            <div class="role">${msg.role === 'user' ? '👤 You' : '🤖 AI Assistant'}</div>
            <div class="content">${escapeHtml(msg.content)}</div>
          </div>
        `).join('')}
        
        <div class="footer">
          Generated by Document Intelligence AI
        </div>
      </body>
      </html>
    `;

    // Create blob and download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `chat-export-${documentName || 'document'}-${Date.now()}.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.success('Chat exported successfully! 📄');
  };

  return (
    <button
      onClick={handleExport}
      className="flex items-center gap-2 px-3 py-2 text-sm rounded-lg
                 bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600
                 text-gray-700 dark:text-gray-200 transition-colors"
      title="Export chat to HTML"
    >
      <DocumentArrowDownIcon className="h-4 w-4" />
      <span className="hidden sm:inline">Export</span>
    </button>
  );
};

// Helper function to escape HTML
function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

export default ExportChat;
